### ISSUE TITLE
Video is 1-pixel off towards the left

### ISSUE THREAD

**Issue by nippur72** [gyurco/VIC20_MiST#13]
Running [this test program](https://github.com/gyurco/VIC20_MiST/files/3109047/timer_pal.zip) doesn't look the same as in real hardware or VICE. The leftmost violet box should NOT be close to the cyan border, but should have a 1-pixel white margin.

Mist output:
![image](https://user-images.githubusercontent.com/2598443/56606815-5a760900-6607-11e9-9ce0-ac973f02f27e.png)

Real VIC-20:
![image](https://user-images.githubusercontent.com/2598443/56606759-3ca8a400-6607-11e9-9bf7-a375c164aae9.png)

VICE emulator:
![image](https://user-images.githubusercontent.com/2598443/56606604-dd4a9400-6606-11e9-9b21-71b48740ef33.png)

I assume it is something related to the 6561 (it might be timer/6522 as well, but I think it's less likely).

I tried to tweak the `K_OFFSET` value that controls horizontal centering, but it seems that it must be a multiple of 4, so I wasn't able to move the screen by 1-pixel easily.

**Comment by gyurco** [comment]
I'm not really familiar with the VIC chip, have to do some debugging what this test do. 
But if turns out it's the timer, then I would be happy to finally have a VIA which works equally 

well both in VIC20 and 1541.

**Comment by lroby74** [comment]
Maybe these links may help you about VIC chip?

http://tinyvga.com/6561

&

https://www.mdawson.net/vic20chrome/display/mos_6560_6561_vic.pdf

I hope so..

**Comment by gyurco** [comment]
I think I already used those references for implementing NTSC/PAL timing differences. Btw, is there a source code for this test prg? Or what debugger are you using? I didn't find any good VIC20 debugger, except one in JavaScript, but I couldn't load that test into it. Recording the CPU input/output in SignalTap, then manually disassemble the code is very tiresome :)

**Comment by nippur72** [comment]
the source code is [here](https://github.com/nippur72/8-bit-projects/blob/master/vic20-raster-boxes/timer.lm), it's an example I have found in a VIC-20 forum.

Anyway I don't think it's a timer issue -- more likely is the screen centering that is off by 1 pixel. Unfortunately `K_OFFSET` can be easily changed only in multiples of 4.

**Comment by gyurco** [comment]
I'm not sure, but in this VIA, lots of things are happening at ENA4, which is 4x of the real VIA clock. Maybe that makes the interrupt happen sooner.

**Comment by gyurco** [comment]
Ok, the 6561 datasheet helped a bit: data transfers occurring at 1MHz clock negative edge.

**Comment by lroby74** [comment]
I am trying Mist now and image is correct

**Comment by nippur72** [comment]
fantastic thanks!
