### ISSUE TITLE
Load *.PRG has regressed

### ISSUE THREAD

**Issue by nippur72** [gyurco/VIC20_MiST#16]
I think something went wrong with `ioctl_reg_inject_state` after TAP has been added to the core.

When you load a `.PRG` basic program, the basic pointers are no longer set, so running it cause an error due to variables overwriting the basic text space. 

(BTW You can see the same behavior in the C64 core which doesn't have the feature of setting the pointers after load).

**Comment by gyurco** [comment]
Do you have an example BASIC program in .prg? The system variables area not in SDRAM, it shouldn't be affected.

**Comment by nippur72** [comment]
I was wrong, the regression was before the TAP, but I can't tell exactly when it happened.

You can try [this basic program](https://github.com/nippur72/8-bit-projects/blob/master/vic20-viznut-pwp-soundtest/test.prg). Run it, choose "0" then "S" then hit "X". An error message will appear. Old versions of the core can run it without errors. 

The problem is that loading a "*.PRG" does not set the $2d pointer any longer, it always stays at 4099. 
```
PRINT PEEK(45)+PEEK(46)*256
 4099
READY.
```

**Comment by gyurco** [comment]
I think ioctl_internal_memory_wr misses ioctl_reg_inject_state, will correct it when I'll be at home.

**Comment by gyurco** [comment]
I think it works now.
