### ISSUE TITLE
Matrix graphical corruption

### ISSUE THREAD

**Issue by Chris5523** [gyurco/VIC20_MiST#17]
When starting a new level in Matrix the last vertical line of pixels on the right of the screen is white and only becomes red when the level starts. This was not the case on real hardware, here the whole grid was red.

The expected behavior can be seen in these 2 videos captured on real hardware.
https://www.youtube.com/watch?v=ye1QhE2Lv18
https://www.youtube.com/watch?v=pkIVUBeItZc

**Comment by gyurco** [comment]
I know that VIC-I is not perfect. Lance Ewing reverse-engineered the chip, one day I'll rewrite it according to his findings.

**Comment by gyurco** [comment]
Fixed
