### ISSUE TITLE
B/W image on PAL CRT display and composite video

### ISSUE THREAD

**Issue by nippur72** [gyurco/VIC20_MiST#3]
Hi, I'm using this core on the "Mistica" board which is essentially a Mist board with composite video output made by a AD724 converter chip.

The problem is that I get a monochrome image when using the composite output. And when I reset the core from OSD, or switch back and forth from PAL to NTSC, I get some colors but they are wrong in chroma.

Other cores (like C64) are displayed correctly and also the VGA output of this core is correct. Only the composite output is wrong.

Some say it might be timings not being perfectly aligned with the standard PAL frequency. 

Do you have any clue about this issue?

Attached: the B/W image after booting the core, and the wrong colors after resetting from OSD:

![image](https://user-images.githubusercontent.com/2598443/55072470-7b405280-508b-11e9-9acd-a798d50ec250.png)

![image](https://user-images.githubusercontent.com/2598443/55072480-85625100-508b-11e9-8f0c-706c27c9a09b.png)

**Comment by gyurco** [comment]
I cannot check it myself, the PLLs are set to the original VIC20 frequency. Who has such a board can try to tweak the PLL frequencies, maybe a minimal adjusment can make it work. Is it wrong in both PAL and NTSC modes?

**Comment by nippur72** [comment]
I tried to modify the clock frequency but it's still monochrome. And yes, it's wrong in both PAL and NTSC. C16/Plus4 cores have the same issue, but the C64 is good for some reason. I will look at that one trying to figure out what's wrong.

**Comment by gyurco** [comment]
Maybe you can try to change "Current_strength" assignment from 4MA to 8MA for the RBG signals.

**Comment by nippur72** [comment]
unfortunately that doesn't work, but I think I have found the source of the problem.

It might be the `vysnc` signal that extends too much, interfering with the color burst signal (canceling it or making it shift in level). Indeed if put `vsync = 0`, I get the correct colors back, but of course an unstable image too.

My theory is that in VGA-to-SCART a too long `vsync` doesn't matter much because it can't conflict with color as they are on separate pins (csync and R,G,B). But in a video composite cable `vsync` is added to the color burst signal, so if it's `vsync=1` during the color burst period then the color burst gets an increase in level. 

I will try to fix it myself, but I need to better understand video signal generation first 😄

**Comment by gyurco** [comment]
I don't know how the AD724 is connected, but in 15kHz mode, the HSync pin has a composite sync, and VSync=1 because SCART needs it for toggling something. So what AD724 does with VSync at all? But you can change CSync polarity, that will make it '0' during active line, and '1' during sync.

**Comment by nippur72** [comment]
After spending the whole day in the wrong direction, I've finally found it! See my description in the pull request.
